---
title: "Customer Personality Analysis"
author: "Junqian Zhang"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(lubridate)
library(nycflights13)
```

# Data Loading
```{r, echo=FALSE, warning=FALSE}
data <- read.csv('marketing_data.csv')
data <- select(data, -c('ID', 'AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'Response', 'Country', 'Complain', 'Recency', 'NumDealsPurchases', 'NumWebVisitsMonth'))
data$Income <- as.numeric(gsub('[$,]', '', data$Income))
data$Age <- 2021-data$Year_Birth
data$Dt_Customer <- as.Date(data$Dt_Customer, '%m/%d/%y')
data$Seniority <- as.numeric(ymd('2021-09-01') - data$Dt_Customer)
data$Children <- data$Kidhome + data$Teenhome
data <- select(data, -c('Year_Birth', 'Dt_Customer', 'Teenhome', 'Kidhome'))
data <- na.omit(data)
summary(data)
```

# Living State
```{r,echo=FALSe, warning=FALSE}
data <- filter(data, Marital_Status!= "Absurd" & Marital_Status!="YOLO")
data$Living <- case_when(data$Marital_Status == 'Married' ~ 'couple', data$Marital_Status == 'Together' ~ 'couple', data$Marital_Status == 'Alone' ~ 'single', data$Marital_Status == 'Divorced' ~ 'single', data$Marital_Status == 'Together' ~ 'couple', data$Marital_Status == 'Widow'~'single', data$Marital_Status == 'Single'~'single')
data <- select(data, -"Marital_Status")
```

# Education
```{r,echo=FALSe, warning=FALSE}
data[data=='2n Cycle'] <- 'Master'
data[data=='Basic'] <- 'Graduation'
```

```{r, echo=FALSE, warning=FALSE}
quantile(data$MntWines, 0.99)
quantile(data$MntFruits, 0.99)
quantile(data$MntMeatProducts, 0.99)
quantile(data$MntFishProducts, 0.99)
quantile(data$MntSweetProducts, 0.99)
quantile(data$MntGoldProds, 0.99)
quantile(data$Age, 0.99)

quantile(data$NumWebPurchases, 0.99)
quantile(data$NumCatalogPurchases, 0.99)
quantile(data$NumStorePurchases, 0.99)

quantile(data$Income, 0.99)
```

```{r, echo=FALSE, warning=FALSE}
data <- filter(data, MntWines <= 1285)
data <- filter(data, MntFruits <=172)
data <- filter(data, MntMeatProducts <= 914.78)
data <- filter(data, MntFishProducts <=226.78)
data <- filter(data, MntSweetProducts <=176)
data <- filter(data, MntGoldProds <=226.67)
data <- filter(data, NumWebPurchases <= 11)
data <- filter(data, NumCatalogPurchases <= 10.85)
data <- filter(data, NumStorePurchases <= 13)
data <- filter(data, Income <= 94462.32 )
data <- filter(data, Age <= 76 )
```

```{r, echo=FALSE, warning=FALSE}
data_product <- select(data, c('MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds'))
data <- select(data, -c('MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds'))
summary(data_product)
summary(data)
```

```{r, echo=FALSE, warning=FALSE}
library(corrplot)
cors <- cor(data[, -c(1,9)])
corrplot(cors, type = 'upper', tl.col = "black", tl.srt =100, method='number',number.cex = 0.5)
```


# Product Feature

## PCA of product features and interpretation
```{r, echo=FALSE, warning=FALSE}
product_scale <- scale(data_product)
means<-colMeans(product_scale)
sds<-apply(product_scale,2,sd)
descr<-round(cbind(means,sds),2)

eigenval <- eigen(cor(product_scale))$values
eigenvec <- eigen(cor(product_scale))$vectors
#screediagram
eigen_dataframe <- data.frame(c(1:6), eigenval)
eigen_plot <- ggplot(data = eigen_dataframe, aes(x=as.factor(eigen_dataframe[,1]), y = eigen_dataframe[,2]))+
  geom_point(size=5)+
  geom_hline(yintercept = 1, color = "green", size= 2.5)+
  xlab("Components")+
  ylab("Eigevalue")
eigen_plot

#percentage of explained variance by each component 
eigen_power<-eigenval/6
eigenpower_dataframe<-data.frame(c(1:6),cumsum(eigen_power))
power_plot <- ggplot(data = eigenpower_dataframe, aes(x=as.factor(eigenpower_dataframe[,1]), y = eigenpower_dataframe[,2]))+
  geom_point(size=5)+
  geom_hline(yintercept = 0.8, color = "green", size= 2.5)+
  xlab("Components")+
  ylab("Variance explained")
power_plot

#Summary description of eigenvalue and eigenvectors in correspondence of variables
eigenvecdf <- data.frame(round(eigenvec[,1:3],3), row.names=colnames(data_product))
colnames(eigenvecdf)<-c("Comp1","Comp2","Comp3")
eigendf<-rbind(eigenvecdf,eigenval[1:3])
rownames(eigendf)[7]<-"EIGENVALUE"

comp<-round(cbind(eigenvec[,1]*sqrt(eigenval[1]),eigenvec[,2]*sqrt(eigenval[2]),eigenvec[,3]*sqrt(eigenval[3])),3)
rownames(comp)<-row.names(descr)
colnames(comp)<-c("Comp1","Comp2","Comp3")
comp_var<-rbind(comp,eigen_power[1:3])
rownames(comp_var)[6]<-"% of VAR explained"
communality<-comp[1:6,1]^2+comp[1:6,2]^2+comp[1:6,3]^2
comp_comu<-cbind(comp[1:6,],communality)
comp_comu
```
## Interpretation of new clusters
```{r, echo=FALSE, warning=FALSE}
punteggi_3 <- product_scale%*%eigenvec[,1:3]
product.k <- data.frame("component1" = punteggi_3[,1], "component2" = punteggi_3[,2], "component3" = punteggi_3[,3])
library(factoextra)
fviz_nbclust(product.k, kmeans, method = "wss") +
    geom_vline(xintercept = 4, linetype = 2)+
  labs(subtitle = "Elbow method")
set.seed(42)
product_cluster <- kmeans(product.k,4)

product.k["cluster"] <- as.factor(product_cluster$cluster)
c1 <- ggplot(product.k, aes(x=cluster, y=component1, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "Component 1", x="Cluster")

c2 <- ggplot(product.k, aes(x=cluster, y=component2, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "Component 2", x="Cluster")

c3 <- ggplot(product.k, aes(x=cluster, y=component3, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "Component 3", x="Cluster")

figure <- ggarrange(c1, c2, c3, ncol=3, nrow=1)


data["Product"] <- as.factor(product_cluster$cluster)
```

# Clustering
```{r, echo=FALSE, warning=FALSE}
data$Product <- as.factor(data$Product)
data$Education <- as.factor(data$Education)
data$Living <- as.factor(data$Living)
data$Product <- case_when(data$Product == 1 ~ 'active shopper', data$Product == 2 ~ 'wine lover', data$Product == 3 ~ 'gold lover', data$Product == 4 ~ 'inactive shopper')
data$Product <- as.factor(data$Product)
summary(data)
```

```{r, echo=FALSE, warning=FALSE}
b1 <- ggplot(data, aes(x = Education)) + ylab(NULL) +
  geom_bar(color="darkblue", fill="lightblue")
  
b2 <- ggplot(data, aes(x = Living)) + ylab(NULL) +
  geom_bar(color="darkblue", fill="lightblue")

b3<- ggplot(data, aes(x = Product)) + ylab(NULL) +
  geom_bar(color="darkblue", fill="lightblue")

figure <- ggarrange(b1,b2,b3,ncol=3, nrow=1)

```


## Distance Matrix
```{r, echo=FALSE, warning=FALSE}
library(StatMatch)
data_s <- cbind(data.frame(scale(data[,2:8])),select(data, c('Education', 'Product', 'Living')))
gower_dist <- gower.dist(data)
d <- as.dist(gower_dist)
# load(file = "gower_dist_marvel.rda")
```

## Ward linkage
```{r, echo=FALSE, warning=FALSE}
hc_ward<- hclust(d,method="ward.D2")
x1 <- cutree(hc_ward, k=3)
x2 <- cutree(hc_ward, k=4)
x3 <- cutree(hc_ward, k=5)
```



## Dendrogram
```{r, echo=FALSE, warning=FALSE}
plot(hc_com, labels = rownames(data_s),hang=-5, cex = 0.6)
rect.hclust(hc_ward,k=4,border=c("orange","green","blue", "red"))
```

# Data Visualization

## categorical variables
```{r, echo=FALSE, warning=FALSE}
data_s$cluster <- as.factor(x2)
library(dplyr)
ed <- data_s %>% 
  group_by(cluster, Education) %>% 
  dplyr::summarise(count = n()) %>% 
  dplyr::mutate(perc = count/sum(count)) %>%
ggplot(aes(x = cluster, y = perc*100, fill = Education)) +
  geom_bar(stat="identity", width = 0.7) +
  labs(x = "Clusters", y = "percentage", fill = "Education") +
  theme_minimal(base_size = 14) + 
  theme(legend.title = element_text(size = 10), 
               legend.text = element_text(size = 10),
        axis.title = element_text(size = 10)) +
  scale_fill_manual(values=c("#ff9999","#ccccff","#00ccff"))

living <- data_s %>% 
  group_by(cluster, Living) %>% 
  dplyr::summarise(count = n()) %>% 
  dplyr::mutate(perc = count/sum(count)) %>%
ggplot(aes(x = cluster, y = perc*100, fill = Living)) +
  geom_bar(stat="identity", width = 0.7) +
  labs(x = "Clusters", y = "percentage", fill = "Living") +
  theme_minimal(base_size = 14) + 
  theme(legend.title = element_text(size = 10), 
               legend.text = element_text(size = 10),
        axis.title = element_text(size = 10)) +
  scale_fill_manual(values=c("#ff9999","#ccccff"))

prod <- data_s %>% 
  group_by(cluster, Product) %>% 
  dplyr::summarise(count = n()) %>% 
  dplyr::mutate(perc = count/sum(count)) %>%
ggplot(aes(x = cluster, y = perc*100, fill = Product)) +
  geom_bar(stat="identity", width = 0.7) +
  labs(x = "Clusters", y = "percentage", fill = "Product") +
  theme_minimal(base_size = 14) + 
  theme(legend.title = element_text(size = 10), 
               legend.text = element_text(size = 10),
        axis.title = element_text(size = 10)) +
  scale_fill_manual(values=c("#ff9999","#ccccff","#00ccff", "#99ffff"))
```

## numeric variables
```{r, echo=FALSE, warning=FALSE}
data$cluster <- as.factor(x2)
b1 <- ggplot(data, aes(x=cluster, y=Age, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "Age", x="Cluster")
b2 <- ggplot(data, aes(x=cluster, y=Income, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "Income", x="Cluster")
b3 <- ggplot(data, aes(x=cluster, y=NumWebPurchases, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "NumWebPurchases", x="Cluster")
b4 <- ggplot(data, aes(x=cluster, y=NumCatalogPurchases, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "NumCatalogPurchases", x="Cluster")
b5 <-ggplot(data, aes(x=cluster, y=NumStorePurchases, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "NumStorePurchases", x="Cluster")

b6 <- ggplot(data, aes(x=cluster, y=Seniority, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "Seniority", x="Cluster")
b7 <- ggplot(data, aes(x=cluster, y=Children, col=cluster)) +
  theme(legend.position="none") +
  geom_boxplot(varwidth = TRUE) + 
  theme(legend.title = element_text(size = 10), 
        legend.text = element_text(size = 8),
        axis.title = element_text(size = 8)) +
  labs(y = "Children", x="Cluster")
figure<- ggarrange(b1,b2,b3,b4,b5,b6,b7,ncol=3, nrow=3)
```




